version: '3.8'

services:
  # Aplicação Spring Boot
  api-investimentos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-investimentos-brasileira
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - investimentos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  investimentos-network:
    driver: bridge

volumes:
  # Volume para persistência de dados (se necessário no futuro)
  investimentos-data:
